name: Deploy app

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check:
    name: Deploy server
    runs-on: self-hosted

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install packages
        run: source ~/.nvm/nvm.sh && nvm use 18 && npm install

      - name: 'Create env file'
        run: |
          touch .env
          echo MAPBOX_KEY=${{ secrets.MAPBOX_KEY }} >> .env
          cat .env

      - name: Build app
        run: source ~/.nvm/nvm.sh && nvm use 18 && NODE_ENV=production CONFIG_ENV=prod npm run build

      - name: Replace app
        run: cd ../ && rm -rf build && cp -r ${{ github.event.repository.name }} build && rm -rf latest && ln -s build latest

      - name: Restart SSR
        run: source ~/.nvm/nvm.sh && nvm use 18 && pm2 restart ribachenko.com

      - name: Wait 5s
        run: sleep 5

      - name: Generate PDF
        run: source ~/.nvm/nvm.sh && nvm use 18 && npm run get:pdf && cp ./static/cv.pdf ../latest/build/client && cp ./static/cv-short.pdf ../latest/build/client

      - name: Restart SSR once again
        run: source ~/.nvm/nvm.sh && nvm use 18 && pm2 restart ribachenko.com
